apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: notes-app
spec:
  selector:
    matchLabels:
      app: notes-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app-1
          env:
            - name: HOST
              value: mysql.notes-app.svc.cluster.local
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-app-secret
                  key: PASSWORD
            - name: MYSQL_PORT
              value: "3306"
          image: ereziko/the-notes-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: notesappservice 
  namespace: notes-app
spec:
  type: ClusterIP
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000











