name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get short commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: create network 
        run: docker network create --driver bridge --subnet 172.111.10.0/24 --gateway 172.111.10.1 test_network
             docker network inspect test_network ‏

      - name: run test_db 
        run: docker run -d --name test -e MYSQL_ROOT_PASSWORD=root --network test_network --ip 172.111.10.10  ereziko/custom-db:final

      - name: test code
        run: python3 test.py

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ereziko/the-notes-app:${{ steps.commit_hash.outputs.hash }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ereziko/the-notes-app:${{ steps.commit_hash.outputs.hash }}

