name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ereziko/the-notes-app:$(date +%s)

      # - name: Test Docker image
      #   run: docker run ereziko/the-notes-app:$(date +%s) python -m unittest discover

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag ereziko/the-notes-app:$(date +%s) ereziko/the-notes-app:github
          docker push ereziko/the-notes-app:github
